Proiect/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Proiect.Data;
using Proiect.Models;

namespace Proiect.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public CategoriesController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager
        )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public ActionResult Index(Category? cat)
        {
            var categories = from category in db.Categories
                             orderby category.CategoryName
                             select category;
            ViewBag.Categories = categories;

            if (TempData.ContainsKey("message"))
            {
                ViewBag.Msg = TempData["message"].ToString();
            }

            SetAccessRights();

            return View(cat);
        }

        
        [HttpPost]
        //[Authorize(Roles = "Admin,Moderator")]
        public ActionResult New(Category cat)
        {
            if(ModelState.IsValid)
            {
                db.Categories.Add(cat);
                db.SaveChanges();
                TempData["message"] = "Categoria a fost adaugata";

                return RedirectToAction("Index");
            }
            else
            {
                TempData["message"] = "Categoria nu a putut fi adaugata";
                return RedirectToAction("Index", cat);
            }
        }

        [Authorize(Roles = "Admin,Moderator")]
        public ActionResult Edit(int id)
        {
            Category category = db.Categories.Find(id);
            return View(category);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Moderator")]
        public ActionResult Edit(int id, Category requestCategory)
        {
            Category category = db.Categories.Find(id);

            if (ModelState.IsValid)
            {
                category.CategoryName = requestCategory.CategoryName;
                category.Description = requestCategory.Description;
                db.SaveChanges();
                TempData["message"] = "Categoria a fost editata";

                return RedirectToAction("Index");
            }
            else
            {
                return View(category);
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Moderator")]
        public ActionResult Delete(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            TempData["message"] = "Categoria a fost stearsa";
            return RedirectToAction("Index");
        }

        [NonAction]

        //// Get current user role

        public async Task<string> GetCurrRoleAsync()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var roles = await _userManager.GetRolesAsync(user);
            var role = roles.FirstOrDefault();
            return role;
        }

        private void SetAccessRights()
        {
            ViewBag.AfisareButoane = false;

            if (User.IsInRole("Moderator") || User.IsInRole("Admin"))
            {
                ViewBag.AfisareButoane = true;
            }

        }
    }
}

Proiect/Controllers/FriendsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Proiect.Data;
using Proiect.Models;

namespace Proiect.Controllers
{
    //[Authorize]
    public class FriendsController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public FriendsController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager
        )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index(string? searchString)
        {
            ViewBag.Friends = db.Friends.Include("User").Where(f => f.FriendId == _userManager.GetUserId(User));
            ViewBag.AllUsers = from user in db.ApplicationUsers select user.UserName;
            
            if (searchString != null)
            {
                searchString = searchString.ToLower().Trim();

                var prieteni = from f in db.Friends.Include("User").Where(f => f.FriendId == _userManager.GetUserId(User))
                               select f.User;

                var users = from user in db.ApplicationUsers.Except(prieteni)
                            select new {UserId = user.Id, user.UserName, user.ProfilPrivat};

                users = users.Where(u => u.UserName.ToLower().Contains(searchString));

                ViewBag.Users = users;
            }

            if (TempData.ContainsKey("message"))
            {
                ViewBag.Msg = TempData["message"].ToString();
            }


            return View();
        }
    }
}

Proiect/Controllers/NotificationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Proiect.Data;
using Proiect.Models;

/*
 *  Functionalitati actuale:
 *      ^ Afisare notificari !!!! aici ar trebui sortate sa le afiseze pe cele necitite mai intai
 *      ^ Marcare drept citita
 *      ^ Marcare toate drept citite
 *      ^ Confirmare cerere - asta la aderare grup
 *      ^ Respingere cerere - asta la aderare grup
 *      
 *  Deci mai trebuie bagate cererile de prietenie aici si in Controllerul de useri
 *  
 *  Deci ma culc
 *  
 *  Deci am facut si prieteni. Problema majora este ca o relatie trebuie bagata de 2 ori ca sunt proasta si nu stiu
 *      cum sa fac sa pot avea 2 legaturi in asociativa ca imi da eroare la Add-Migration
 *      
 *  In fine
 * 
 * 
 */

namespace Proiect.Controllers
{
    [Authorize]
    public class NotificationsController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public NotificationsController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager
        )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var notifs = db.Notifications.Include("User").Include("Group").Where(n => n.UserId == _userManager.GetUserId(User));
            ViewBag.Notifs = notifs;

            return View();
        }

        public IActionResult MarkAsSeen(int id)
        {
            var notif = db.Notifications.Find(id);
            notif.Seen = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Confirm(int id, int UserId)
        {
            var notif = db.Notifications.Find(id);
            if (notif.GroupId == null)
            {
                var user1 = db.Users.Find(notif.FromUserId);
                var user2 = db.Users.Find(notif.UserId);
                Friend Relation1 = new Friend();
                Friend Relation2 = new Friend();
                Relation1.UserId = user1.Id;
                Relation1.User = user1;
                Relation1.FriendId = user2.Id;
                Relation2.UserId = user2.Id;
                Relation2.User = user2;
                Relation2.FriendId = user1.Id;
                db.Friends.Add(Relation1);
                db.Friends.Add(Relation2);
                db.Notifications.Remove(notif);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var group = db.Groups.Find(notif.GroupId);
            var user = db.Users.Find(notif.FromUserId);
            var userInGroupVerif = db.ApplicationUsersInGroups
                .Where(m => m.UserId == user.Id && m.GroupId == group.Id)
                .FirstOrDefault();
            
            if (userInGroupVerif != null)
            {
                db.Notifications.Remove(notif);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            if (user.Id == _userManager.GetUserId(User))
            {
                db.Notifications.Remove(notif);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var userInGroup = new ApplicationUsersInGroups();
            userInGroup.GroupId = group.Id;
            userInGroup.Group = group;
            userInGroup.UserId = user.Id;
            userInGroup.User = user;
            userInGroup.Confirmed = true; /// De scos asta si bagat data in asociativa
            db.ApplicationUsersInGroups.Add(userInGroup);
            db.Notifications.Remove(notif);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Decline(int id)
        {
            var notif = db.Notifications.Find(id);
            db.Notifications.Remove(notif);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Proiect/Views/Shared/GroupInfo.cshtml
<div class="card-body">

    <h4 class="card-title">@Model.GroupName</h4>
    <span>Creat de <a href="/ApplicationUsers/Show/@Model.User.Id"> <i class="bi bi-person-video"></i> @Model.User.UserName</a> pe @Model.Date.ToString("dd/MM/yyyy")</span>

    @if (Model.Description != null)
    {
        <br /> <br />
        <div class="card-text">@Model.Description</div>

    }

</div>

Proiect/Views/Shared/Pagination.cshtml
@{
    var _currentPage = (int)ViewBag.CurrentPage;
    var _perPage = (int)ViewBag.PerPage;
    var _totalItems = (int)ViewBag.TotalItems;
    var _totalPages = (int)Math.Ceiling((decimal)_totalItems / _perPage);
    var _controller = (string)ViewBag.Controller;
    var _action = (string)ViewBag.Action;
}


    <div class="d-flex justify-content-center">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item @(_currentPage == 1 ? "disabled" : "")">
                    <a class="page-link" href="@Url.Action(_action, _controller, new { page = _currentPage - 1})">Anterior</a>
                </li>
                @for (int i = 1; i <= _totalPages; i++)
                {
                    <li  class="page-item @(_currentPage == i ? "active" : "")">
                        <a class="page-link" href="@Url.Action(_action, _controller, new { page = i})">@i</a>
                    </li>
                }
                <li class="page-item @(_currentPage >= _totalPages ? "disabled" : "")">
                    <a class="page-link" href="@Url.Action(_action, _controller, new { page = _currentPage + 1})">Urmator</a>
                </li>
            </ul>
        </nav>

    </div>

Proiect/Views/Shared/PostInfo.cshtml
<div class="card-body">
   
    <h4 class="cart-title">@Model.Title</h4>
    <span>@Model.Date</span>
    <br /> <br />
    <div class="card-text">@Model.Content</div>
    <br />
    <div class="d-flex flex-row justify-content-between">
        <div><i class="bi bi-tag"></i> @Model.Category.CategoryName</div>
        <div><a href="/ApplicationUsers/Show/@Model.User.Id"><i class="bi bi-person-workspace"></i>  @Model.User.UserName</a></div>
    </div>

</div>

Proiect/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Proiect.Models
@inject SignInManager<ApplicationUser> SignInManager;
@inject UserManager<ApplicationUser> UserManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proiect</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Proiect.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand nav-link text-light" asp-area="" asp-controller="Posts" asp-action="Index">Proiect</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Posts" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Groups" asp-action="Index">Grupuri</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Categories" asp-action="Index">Categorii</a>
                        </li>

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="ApplicationUsers" asp-action="Show" asp-route-id="@UserManager.GetUserId(User)">Profil</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Notifications" asp-action="Index" asp-route-id="@UserManager.GetUserId(User)">Notificari</a>
                            </li>
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="ApplicationUsers" asp-action="Index">Utilizatori</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Friends" asp-action="Index">Prieteni</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Proiect - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>